### ISSUE TITLE
What are source maps supposed to look like?

### ISSUE THREAD

**Issue by dustingetz** [specious/clojurescript-nodejs-starter-kit#2]
My source maps don't seem to be working, what should I see here? I expected to at least see "core.cljs line 7" (I coded the NPE on purpose on L7 to see the stack trace)
![image](https://user-images.githubusercontent.com/124158/33047450-bdb53c3e-ce23-11e7-995f-d36bab8a3f68.png)

**Comment by specious** [comment]
Excellent question!

Since I'm new to this myself, I went in to investigate.  I made the same change to `src/app/core.cljs`:
```diff
--- a/src/app/core.cljs
+++ b/src/app/core.cljs
@@ -4,6 +4,7 @@
 (defn main [& args]
+  (let [x nil] (x))
   (println "Abracadabra!"))
```

And got the same runtime error:
```
$ cd target
$ node main.js
/Users/specious/c/clojurescript-nodejs-starter-kit/src/target/main.out/app/core.js:28
x_7585.call(null);
       ^

TypeError: Cannot read property 'call' of null
    at Function.app.core.main.cljs$core$IFn$_invoke$arity$variadic (/Users/specious/c/clojurescript-nodejs-starter-kit/src/target/main.out/app/core.js:28:8)
    at app$core$main (/Users/specious/c/clojurescript-nodejs-starter-kit/src/target/main.out/app/core.js:23:22)
    at Object.cljs$core$apply_to [as apply_to] (/Users/specious/c/clojurescript-nodejs-starter-kit/src/target/main.out/cljs/core.js:11845:81)
    at Function.cljs.core.apply.cljs$core$IFn$_invoke$arity$2 (/Users/specious/c/clojurescript-nodejs-starter-kit/src/target/main.out/cljs/core.js:12100:18)
    at cljs$core$apply (/Users/specious/c/clojurescript-nodejs-starter-kit/src/target/main.out/cljs/core.js:12073:24)
    at Object.<anonymous> (/Users/specious/c/clojurescript-nodejs-starter-kit/src/target/main.out/BCE03FE.js:11:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```

Here's how I got it to work:
```
$ node --inspect-brk main.js
Debugger listening on ws://127.0.0.1:9229/3ab9b847-b947-4742-9ffd-44af8a2247ec
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
```

Then opened Chrome dev tools, which showed the node debugger button, and clicking it opened the node debugger, which allowed me to click `Resume script execution (F8)`, which landed me right on the correct breakpoint in `src/app/core.cljs`:

![nodejs-cljs-breakpoint-with-sourcemap](https://user-images.githubusercontent.com/451178/33234419-7e9d06e2-d1f4-11e7-8f73-052f6fe49c01.png)

**Comment by dustingetz** [comment]
🎉 🎉 🎉 🎉 !!!!!

**Comment by specious** [comment]
I added proper instructions to the README: 21463803f9deed9928953edcfc7c39a8e4902ea7.

@dustingetz, thanks for getting my attention on this topic.
